#!/bin/sh


if [ $EUID = 0 ]
then
	echo "you cannot run this as root"
	exit
fi



cd ~/.local/share/

if [ -d "games/" ]
then
	echo games folder founded
else
	echo creating Games folder
	mkdir games
fi

cd games

if [ -d "opentictactoex" ]
then
	echo removing opentictactoex
	rm -R opentictactoex/
fi


mkdir opentictactoex
cd opentictactoex

if [[ $MACHTYPE == *64* ]]
then
	echo x86_64 detected
	wget https://sourceforge.net/projects/opentictactoex/files/v0.5/OpenTicTacToeX.x86_64/download
else
	echo x86_64 did not detect, using x86
	https://sourceforge.net/projects/opentictactoex/files/v0.5/OpenTicTacToeX.x86/download
fi


mv download opentictactoex
chmod a+x opentictactoex

wget https://can202.github.io/OpenTicTacToeX/src/textures/icon/256icon.png
mv 256icon.png icon.png

echo "[Desktop Entry]
Name=OpenTicTacToeX
Exec=/home/$USER/.local/share/games/opentictactoex/opentictactoex
Icon=/home/$USER/.local/share/games/opentictactoex/icon.png
Type=Application
Categories=Game" >> opentictactoex.desktop

cp opentictactoex.desktop ~/.local/share/applications/

echo "opentictactoex.desktop created"


